spring:
  application:
    name: seat-lock
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
